export default {
    _id: "1111",
    userName: "KaydeLi",
    toCheck: [//等待用户授权的项目
        {
            _id: "0001",
            user_id: "0002",
            userName: "kaydenJobs",
            project_id: "1",
            address: "wuhan hust",
            projectName: "待开放授权项目1",
            title: "申请项目授权",
            date: "2020-02-02",
            status: "waitting",
            authdate: "",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        },
        {
            _id: "0002",
            user_id: "0002",
            userName: "kayden001",
            project_id: "1",
            address: "wuhan hust",
            projectName: "待开放授权项目--2",
            title: "申请项目授权",
            date: "2020-02-02",
            status: "waitting",
            authdate: "",
            description: "测试。",
        },
        {
            _id: "0003",
            user_id: "0002",
            userName: "Smith",
            project_id: "1",
            address: "wuhan hust",
            projectName: "待开放测试",
            title: "申请项目授权",
            date: "2020-02-02",
            status: "waitting",
            authdate: "",
            description: "测试，测试",
        },

    ],
    getChecked: [//用户已开放的项目
        {
            _id: "1",
            user_id: "0002",
            userName: "kayden",
            project_id: "1",
            address: "wuhan hust",
            projectName: "已开放项目-测试-1",
            title: "已授权",
            date: "2020-02-02",
            status: "success",
            authdate: "2020-02-03",
            description: "测试已开放项目1。",
        },
        {
            _id: "2",
            user_id: "0002",
            userName: "Smith",
            project_id: "1",
            address: "wuhan hust",
            projectName: "已开放项目-测试-2",
            title: "已授权",
            date: "2020-02-02",
            status: "fail",
            authdate: "2020-02-03",
            description: "测试已开放项目2。",
        }
    ]
}