export default {
    _id: "0001",
    userName: "KaydeLi",
    toCheck: [//等待用户授权的项目
        {
            _id: "0001",
            user_id: "0002",
            userName: "kayden",
            project_id: "1",
            address: "wuhan hust",
            projectName: "address",
            title: "申请项目授权",
            date: "2020-02-02",
            status: "waitting",
            authdate: "",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        },
        {
            _id: "0002",
            user_id: "0002",
            userName: "kayden",
            project_id: "1",
            address: "wuhan hust",
            projectName: "address",
            title: "申请项目授权",
            date: "2020-02-02",
            status: "waitting",
            authdate: "",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        },
        {
            _id: "0003",
            user_id: "0002",
            userName: "kayden",
            project_id: "1",
            address: "wuhan hust",
            projectName: "address",
            title: "申请项目授权",
            date: "2020-02-02",
            status: "waitting",
            authdate: "",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        },

    ],
    toQuest: [//用户正在请求查看的项目
        {
            _id: "01",
            user_id: "0002",
            userName: "kayden",
            project_id: "1",
            address: "wuhan hust",
            projectName: "address",
            title: "授权",
            date: "2020-02-02",
            status: "waitting",
            authdate: "",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        },
        {
            _id: "02",
            user_id: "0002",
            userName: "kayden",
            address: "wuhan hust",
            project_id: "1",
            projectName: "address",
            title: "授权",
            date: "2020-02-02",
            status: "waitting",
            authdate: "",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        },
        {
            _id: "03",
            user_id: "0002",
            userName: "kayden",
            project_id: "1",
            address: "wuhan hust",
            projectName: "address",
            title: "授权",
            date: "2020-02-02",
            status: "waitting",
            authdate: "",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        },
    ],
    getChecked: [//用户已开发的项目
        {
            _id: "1",
            user_id: "0002",
            userName: "kayden",
            project_id: "1",
            address: "wuhan hust",
            projectName: "address",
            title: "已授权",
            date: "2020-02-02",
            status: "done",
            authdate: "2020-02-03",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        },
        {
            _id: "2",
            user_id: "0002",
            userName: "kayden",
            project_id: "1",
            address: "wuhan hust",
            projectName: "address",
            title: "已授权",
            date: "2020-02-02",
            status: "done",
            authdate: "2020-02-03",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        }
    ],
    getAuthed: [//用户已获得授权的项目
        {
            _id: "3",
            user_id: "0002",
            userName: "kayden",
            project_id: "1",
            address: "wuhan hust",
            projectName: "address",
            title: "已获取授权",
            date: "2020-02-02",
            status: "done",
            authdate: "2020-02-03",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        },
        {
            _id: "4",
            user_id: "0002",
            userName: "kayden",
            project_id: "1",
            address: "wuhan hust",
            projectName: "address",
            title: "已获取授权",
            date: "2020-02-02",
            status: "done",
            authdate: "2020-02-03",
            description: "测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试，测试。",
        },
    ]
}