import {
    points1,
    points2,
    points3,
    points4,
    points5,
    points6,
    points7,
    points8,
    points9,
    points10,
    points11,
    points12,
    points13,
    points14,
    points15,
    points16,
    points17,
    points18,
    points19,
    points20,
    points21,
    points22,
    points23,
    points24,
    points25,
    points26,
    points27,
    points28,
    points29,
    points30,
    points31,
    points32,
    points33,
    points34,
    points35,
    points36,
    points37,
    points38,
    points39,
    points40,
    points41,
    points42,
    points43,
    points44,
    points45,
    points46,
    points47,
    points48,
    points49,
    points50,
    points51,
    points52,
    points53,
    points54,
    points55,
    points56,
    points57,
    points58,
    points59,
    points60,
    points61,
    points62,
    points63,
    points64,
    points65,
    points66,
    points67,
    points68,
    points69,
    points70,
    points71,
    points72,
    points73,
    points74,
    points75,
    points76,
    points77,
    points78,
    points79,
    points80,
    points81,
    points82,
    points83,
    points84,
    points85,
    points86,
    points87,
    points88,
    points89,
    points90,
} from './point.js'

export const site1 = {
    name: "site1",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { _id: "1", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-1", type: "stress-x", group: ["关键点", "常预警"], unit: "MPa", value: points1 },
        { _id: "2", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-2", type: "angle-y", group: [], unit: "秒", value: points2 },
        { _id: "3", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-3", type: "stress-y", group: [], unit: "MPa", value: points3 },
        { _id: "4", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-4", type: "display-y", group: [], unit: "mm", value: points4 },
        { _id: "5", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-5", type: "angle", group: ["常预警"], unit: "秒", value: points5 },
        { _id: "6", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-6", type: "stress-x", group: [], unit: "MPa", value: points6 },
        { _id: "7", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-7", type: "angle-y", group: [], unit: "秒", value: points7 },
        { _id: "8", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-8", type: "stress-y", group: [], unit: "MPa", value: points8 },
        { _id: "9", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-9", type: "display-y", group: [], unit: "mm", value: points9 },
        { _id: "10", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-10", type: "angle", group: [], unit: "秒", value: points10 },
        { _id: "11", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-11", type: "stress-x", group: [], unit: "MPa", value: points11 },
        { _id: "12", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-12", type: "angle-y", group: ["常预警"], unit: "秒", value: points12 },
        { _id: "13", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-13", type: "stress-y", group: [], unit: "MPa", value: points13 },
        { _id: "14", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-14", type: "display-y", group: ["已停用", "故障", "常预警"], unit: "mm", value: points14 },
        { _id: "15", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-1-15", type: "angle", group: [], unit: "秒", value: points15 }
    ]
}
export const site2 = {
    name: "site2",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { _id: "16", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-1", type: "stress-x", group: [], unit: "MPa", value: points16 },
        { _id: "17", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-2", type: "angle-y", group: [], unit: "秒", value: points17 },
        { _id: "18", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-3", type: "stress-y", group: ["常预警"], unit: "MPa", value: points18 },
        { _id: "19", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-4", type: "display-y", group: [], unit: "mm", value: points19 },
        { _id: "20", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-5", type: "angle", group: [], unit: "秒", value: points20 },
        { _id: "21", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-6", type: "stress-x", group: [], unit: "MPa", value: points21 },
        { _id: "22", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-7", type: "angle-y", group: [], unit: "秒", value: points22 },
        { _id: "23", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-8", type: "stress-y", group: [], unit: "MPa", value: points23 },
        { _id: "24", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-9", type: "display-y", group: [], unit: "mm", value: points24 },
        { _id: "25", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-10", type: "angle", group: [], unit: "秒", value: points25 },
        { _id: "26", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-11", type: "stress-x", group: [], unit: "MPa", value: points26 },
        { _id: "27", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-12", type: "angle-y", group: [], unit: "秒", value: points27 },
        { _id: "28", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-13", type: "stress-y", group: [], unit: "MPa", value: points28 },
        { _id: "29", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-14", type: "display-y", group: [], unit: "mm", value: points29 },
        { _id: "30", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-2-15", type: "angle", group: [], unit: "秒", value: points30 }
    ]
}

export const site3 = {
    name: "site3",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { _id: "31", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-1", type: "stress-x", group: ["已停用"], unit: "MPa", value: points31 },
        { _id: "32", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-2", type: "angle-y", group: [], unit: "秒", value: points32 },
        { _id: "33", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-3", type: "stress-y", group: [], unit: "MPa", value: points33 },
        { _id: "34", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-4", type: "display-y", group: [], unit: "mm", value: points34 },
        { _id: "35", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-5", type: "angle", group: [], unit: "秒", value: points35 },
        { _id: "36", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-6", type: "stress-x", group: [], unit: "MPa", value: points36 },
        { _id: "37", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-7", type: "angle-y", group: [], unit: "秒", value: points37 },
        { _id: "38", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-8", type: "stress-y", group: [], unit: "MPa", value: points38 },
        { _id: "39", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-9", type: "display-y", group: [], unit: "mm", value: points39 },
        { _id: "40", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-10", type: "angle", group: [], unit: "秒", value: points40 },
        { _id: "41", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-11", type: "stress-x", group: ["已停用"], unit: "MPa", value: points41 },
        { _id: "42", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-12", type: "angle-y", group: [], unit: "秒", value: points42 },
        { _id: "43", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-13", type: "stress-y", group: [], unit: "MPa", value: points43 },
        { _id: "44", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-14", type: "display-y", group: [], unit: "mm", value: points44 },
        { _id: "45", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point1-3-15", type: "angle", group: ["已停用"], unit: "秒", value: points45 }
    ]
}

export const site4 = {
    name: "site4",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { _id: "46", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-1", type: "stress-x", group: [], unit: "MPa", value: points46 },
        { _id: "47", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-2", type: "angle-y", group: [], unit: "秒", value: points47 },
        { _id: "48", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-3", type: "stress-y", group: [], unit: "MPa", value: points48 },
        { _id: "49", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-4", type: "display-y", group: [], unit: "mm", value: points49 },
        { _id: "50", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-5", type: "angle", group: [], unit: "秒", value: points50 },
        { _id: "51", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-6", type: "stress-x", group: ["已停用"], unit: "MPa", value: points51 },
        { _id: "52", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-7", type: "angle-y", group: [], unit: "秒", value: points52 },
        { _id: "53", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-8", type: "stress-y", group: [], unit: "MPa", value: points53 },
        { _id: "54", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-9", type: "display-y", group: [], unit: "mm", value: points54 },
        { _id: "55", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-10", type: "angle", group: [], unit: "秒", value: points55 },
        { _id: "56", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-11", type: "stress-x", group: [], unit: "MPa", value: points56 },
        { _id: "57", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-12", type: "angle-y", group: [], unit: "秒", value: points57 },
        { _id: "58", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-13", type: "stress-y", group: [], unit: "MPa", value: points58 },
        { _id: "59", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-14", type: "display-y", group: [], unit: "mm", value: points59 },
        { _id: "60", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-4-15", type: "angle", group: ["故障"], unit: "秒", value: points60 }
    ]
}

export const site5 = {
    name: "site5",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { _id: "61", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-1", type: "stress-x", group: [], unit: "MPa", value: points61 },
        { _id: "62", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-2", type: "angle-y", group: [], unit: "秒", value: points62 },
        { _id: "63", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-3", type: "stress-y", group: [], unit: "MPa", value: points63 },
        { _id: "64", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-4", type: "display-y", group: [], unit: "mm", value: points64 },
        { _id: "65", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-5", type: "angle", group: ["故障", "已停用"], unit: "秒", value: points65 },
        { _id: "66", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-6", type: "stress-x", group: [], unit: "MPa", value: points66 },
        { _id: "67", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-7", type: "angle-y", group: [], unit: "秒", value: points67 },
        { _id: "68", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-8", type: "stress-y", group: [], unit: "MPa", value: points68 },
        { _id: "69", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-9", type: "display-y", group: [], unit: "mm", value: points69 },
        { _id: "70", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-10", type: "angle", group: [], unit: "秒", value: points70 },
        { _id: "71", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-11", type: "stress-x", group: [], unit: "MPa", value: points71 },
        { _id: "72", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-12", type: "angle-y", group: [], unit: "秒", value: points72 },
        { _id: "73", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-13", type: "stress-y", group: [], unit: "MPa", value: points73 },
        { _id: "74", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-14", type: "display-y", group: [], unit: "mm", value: points74 },
        { _id: "75", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-5-15", type: "angle", group: ["故障"], unit: "秒", value: points75 }
    ]
}

export const site6 = {
    name: "site6",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { _id: "76", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-1", type: "stress-x", group: ["故障"], unit: "MPa", value: points76 },
        { _id: "77", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-2", type: "angle-y", group: [], unit: "秒", value: points77 },
        { _id: "78", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-3", type: "stress-y", group: [], unit: "MPa", value: points78 },
        { _id: "79", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-4", type: "display-y", group: ["故障", "已停用"], unit: "mm", value: points79 },
        { _id: "80", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-5", type: "angle", group: [], unit: "秒", value: points80 },
        { _id: "81", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-6", type: "stress-x", group: [], unit: "MPa", value: points81 },
        { _id: "82", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-7", type: "angle-y", group: [], unit: "秒", value: points82 },
        { _id: "83", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-8", type: "stress-y", group: [], unit: "MPa", value: points83 },
        { _id: "84", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-9", type: "display-y", group: [], unit: "mm", value: points84 },
        { _id: "85", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-10", type: "angle", group: [], unit: "秒", value: points85 },
        { _id: "86", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-11", type: "stress-x", group: [], unit: "MPa", value: points86 },
        { _id: "87", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-12", type: "angle-y", group: [], unit: "秒", value: points87 },
        { _id: "88", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-13", type: "stress-y", group: [], unit: "MPa", value: points88 },
        { _id: "89", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-14", type: "display-y", group: [], unit: "mm", value: points89 },
        { _id: "90", notes: "无", ratio: "1.0", limit: "500", threshold: "700", initialError: "0", name: "point2-6-15", type: "angle", group: ["已停用"], unit: "秒", value: points90 }
    ]
}