import {
    points1,
    points2,
    points3,
    points4,
    points5,
    points6,
    points7,
    points8,
    points9,
    points10,
    points11,
    points12,
    points13,
    points14,
    points15,
    points16,
    points17,
    points18,
    points19,
    points20,
    points21,
    points22,
    points23,
    points24,
    points25,
    points26,
    points27,
    points28,
    points29,
    points30,
    points31,
    points32,
    points33,
    points34,
    points35,
    points36,
    points37,
    points38,
    points39,
    points40,
    points41,
    points42,
    points43,
    points44,
    points45,
    points46,
    points47,
    points48,
    points49,
    points50,
    points51,
    points52,
    points53,
    points54,
    points55,
    points56,
    points57,
    points58,
    points59,
    points60,
    points61,
    points62,
    points63,
    points64,
    points65,
    points66,
    points67,
    points68,
    points69,
    points70,
    points71,
    points72,
    points73,
    points74,
    points75,
    points76,
    points77,
    points78,
    points79,
    points80,
    points81,
    points82,
    points83,
    points84,
    points85,
    points86,
    points87,
    points88,
    points89,
    points90,
} from './point.js'

export const site1 = {
    name: "site1",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { id: "sensor1", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-1", type: "stress-x", group: ["关键点", "常预警"], unit: "MPa", value: points1 },
        { id: "sensor2", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-2", type: "angle-y", group: [], unit: "秒", value: points2 },
        { id: "sensor3", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-3", type: "stress-y", group: [], unit: "MPa", value: points3 },
        { id: "sensor4", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-4", type: "display-y", group: [], unit: "mm", value: points4 },
        { id: "sensor5", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-5", type: "angle", group: ["常预警"], unit: "秒", value: points5 },
        { id: "sensor6", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-6", type: "stress-x", group: [], unit: "MPa", value: points6 },
        { id: "sensor7", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-7", type: "angle-y", group: [], unit: "秒", value: points7 },
        { id: "sensor8", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-8", type: "stress-y", group: [], unit: "MPa", value: points8 },
        { id: "sensor9", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-9", type: "display-y", group: [], unit: "mm", value: points9 },
        { id: "sensor10", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-10", type: "angle", group: [], unit: "秒", value: points10 },
        { id: "sensor11", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-11", type: "stress-x", group: [], unit: "MPa", value: points11 },
        { id: "sensor12", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-12", type: "angle-y", group: ["常预警"], unit: "秒", value: points12 },
        { id: "sensor13", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-13", type: "stress-y", group: [], unit: "MPa", value: points13 },
        { id: "sensor14", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-14", type: "display-y", group: ["已停用", "故障", "常预警"], unit: "mm", value: points14 },
        { id: "sensor15", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-1-15", type: "angle", group: [], unit: "秒", value: points15 }
    ]
}
export const site2 = {
    name: "site2",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { id: "sensor16", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-1", type: "stress-x", group: [], unit: "MPa", value: points16 },
        { id: "sensor17", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-2", type: "angle-y", group: [], unit: "秒", value: points17 },
        { id: "sensor18", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-3", type: "stress-y", group: ["常预警"], unit: "MPa", value: points18 },
        { id: "sensor19", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-4", type: "display-y", group: [], unit: "mm", value: points19 },
        { id: "sensor20", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-5", type: "angle", group: [], unit: "秒", value: points20 },
        { id: "sensor21", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-6", type: "stress-x", group: [], unit: "MPa", value: points21 },
        { id: "sensor22", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-7", type: "angle-y", group: [], unit: "秒", value: points22 },
        { id: "sensor23", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-8", type: "stress-y", group: [], unit: "MPa", value: points23 },
        { id: "sensor24", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-9", type: "display-y", group: [], unit: "mm", value: points24 },
        { id: "sensor25", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-10", type: "angle", group: [], unit: "秒", value: points25 },
        { id: "sensor26", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-11", type: "stress-x", group: [], unit: "MPa", value: points26 },
        { id: "sensor27", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-12", type: "angle-y", group: [], unit: "秒", value: points27 },
        { id: "sensor28", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-13", type: "stress-y", group: [], unit: "MPa", value: points28 },
        { id: "sensor29", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-14", type: "display-y", group: [], unit: "mm", value: points29 },
        { id: "sensor30", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-2-15", type: "angle", group: [], unit: "秒", value: points30 }
    ]
}

export const site3 = {
    name: "site3",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { id: "sensor31", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-1", type: "stress-x", group: ["已停用"], unit: "MPa", value: points31 },
        { id: "sensor32", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-2", type: "angle-y", group: [], unit: "秒", value: points32 },
        { id: "sensor33", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-3", type: "stress-y", group: [], unit: "MPa", value: points33 },
        { id: "sensor34", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-4", type: "display-y", group: [], unit: "mm", value: points34 },
        { id: "sensor35", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-5", type: "angle", group: [], unit: "秒", value: points35 },
        { id: "sensor36", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-6", type: "stress-x", group: [], unit: "MPa", value: points36 },
        { id: "sensor37", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-7", type: "angle-y", group: [], unit: "秒", value: points37 },
        { id: "sensor38", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-8", type: "stress-y", group: [], unit: "MPa", value: points38 },
        { id: "sensor39", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-9", type: "display-y", group: [], unit: "mm", value: points39 },
        { id: "sensor40", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-10", type: "angle", group: [], unit: "秒", value: points40 },
        { id: "sensor41", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-11", type: "stress-x", group: ["已停用"], unit: "MPa", value: points41 },
        { id: "sensor42", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-12", type: "angle-y", group: [], unit: "秒", value: points42 },
        { id: "sensor43", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-13", type: "stress-y", group: [], unit: "MPa", value: points43 },
        { id: "sensor44", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-14", type: "display-y", group: [], unit: "mm", value: points44 },
        { id: "sensor45", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point1-3-15", type: "angle", group: ["已停用"], unit: "秒", value: points45 }
    ]
}

export const site4 = {
    name: "site4",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { id: "sensor46", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-1", type: "stress-x", group: [], unit: "MPa", value: points46 },
        { id: "sensor47", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-2", type: "angle-y", group: [], unit: "秒", value: points47 },
        { id: "sensor48", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-3", type: "stress-y", group: [], unit: "MPa", value: points48 },
        { id: "sensor49", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-4", type: "display-y", group: [], unit: "mm", value: points49 },
        { id: "sensor50", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-5", type: "angle", group: [], unit: "秒", value: points50 },
        { id: "sensor51", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-6", type: "stress-x", group: ["已停用"], unit: "MPa", value: points51 },
        { id: "sensor52", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-7", type: "angle-y", group: [], unit: "秒", value: points52 },
        { id: "sensor53", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-8", type: "stress-y", group: [], unit: "MPa", value: points53 },
        { id: "sensor54", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-9", type: "display-y", group: [], unit: "mm", value: points54 },
        { id: "sensor55", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-10", type: "angle", group: [], unit: "秒", value: points55 },
        { id: "sensor56", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-11", type: "stress-x", group: [], unit: "MPa", value: points56 },
        { id: "sensor57", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-12", type: "angle-y", group: [], unit: "秒", value: points57 },
        { id: "sensor58", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-13", type: "stress-y", group: [], unit: "MPa", value: points58 },
        { id: "sensor59", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-14", type: "display-y", group: [], unit: "mm", value: points59 },
        { id: "sensor60", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-4-15", type: "angle", group: ["故障"], unit: "秒", value: points60 }
    ]
}

export const site5 = {
    name: "site5",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { id: "sensor61", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-1", type: "stress-x", group: [], unit: "MPa", value: points61 },
        { id: "sensor62", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-2", type: "angle-y", group: [], unit: "秒", value: points62 },
        { id: "sensor63", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-3", type: "stress-y", group: [], unit: "MPa", value: points63 },
        { id: "sensor64", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-4", type: "display-y", group: [], unit: "mm", value: points64 },
        { id: "sensor65", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-5", type: "angle", group: ["故障", "已停用"], unit: "秒", value: points65 },
        { id: "sensor66", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-6", type: "stress-x", group: [], unit: "MPa", value: points66 },
        { id: "sensor67", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-7", type: "angle-y", group: [], unit: "秒", value: points67 },
        { id: "sensor68", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-8", type: "stress-y", group: [], unit: "MPa", value: points68 },
        { id: "sensor69", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-9", type: "display-y", group: [], unit: "mm", value: points69 },
        { id: "sensor70", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-10", type: "angle", group: [], unit: "秒", value: points70 },
        { id: "sensor71", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-11", type: "stress-x", group: [], unit: "MPa", value: points71 },
        { id: "sensor72", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-12", type: "angle-y", group: [], unit: "秒", value: points72 },
        { id: "sensor73", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-13", type: "stress-y", group: [], unit: "MPa", value: points73 },
        { id: "sensor74", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-14", type: "display-y", group: [], unit: "mm", value: points74 },
        { id: "sensor75", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-5-15", type: "angle", group: ["故障"], unit: "秒", value: points75 }
    ]
}

export const site6 = {
    name: "site6",
    machineinfo: "此设备生产日期为：2016-12-30，参数一为xxx，参数二为xxx。可以测量出位移、加速度等观测值。",
    value: [
        { id: "sensor76", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-1", type: "stress-x", group: ["故障"], unit: "MPa", value: points76 },
        { id: "sensor77", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-2", type: "angle-y", group: [], unit: "秒", value: points77 },
        { id: "sensor78", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-3", type: "stress-y", group: [], unit: "MPa", value: points78 },
        { id: "sensor79", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-4", type: "display-y", group: ["故障", "已停用"], unit: "mm", value: points79 },
        { id: "sensor80", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-5", type: "angle", group: [], unit: "秒", value: points80 },
        { id: "sensor81", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-6", type: "stress-x", group: [], unit: "MPa", value: points81 },
        { id: "sensor82", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-7", type: "angle-y", group: [], unit: "秒", value: points82 },
        { id: "sensor83", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-8", type: "stress-y", group: [], unit: "MPa", value: points83 },
        { id: "sensor84", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-9", type: "display-y", group: [], unit: "mm", value: points84 },
        { id: "sensor85", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-10", type: "angle", group: [], unit: "秒", value: points85 },
        { id: "sensor86", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-11", type: "stress-x", group: [], unit: "MPa", value: points86 },
        { id: "sensor87", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-12", type: "angle-y", group: [], unit: "秒", value: points87 },
        { id: "sensor88", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-13", type: "stress-y", group: [], unit: "MPa", value: points88 },
        { id: "sensor89", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-14", type: "display-y", group: [], unit: "mm", value: points89 },
        { id: "sensor90", notes: "无", ratio: "1.0", limit: "500", threshold: "700", position: [0, 0, 0], initialError: "0", name: "point2-6-15", type: "angle", group: ["已停用"], unit: "秒", value: points90 }
    ]
}